### ISSUE TITLE
dependency-cruiser output wrong path when import the path includes "#"

### ISSUE THREAD

**Issue by azu** [sverweij/dependency-cruiser#459] opened 2021-05-02 23:28 UTC
I've noticed that dependency-cruiser output wrong path when import the path includes "#" like [es5-ext](https://github.com/medikoo/es5-ext).
dependency-cruiser outputs `path/to/index.js#/` instead of `path/to/#/`.

### Expected Behavior

```js
require("es5-ext/array/#/contains");
```

will be resolved as

```
node_modules/es5-ext/array/#/contains
```

### Current Behavior

```js
require("es5-ext/array/#/contains");
```

will be resolved as

```
node_modules/es5-ext/array/index.js#/contains
```

### Steps to Reproduce (for bugs)

Reproduce repository: https://github.com/azu/dependency-cruiser-sharp-bug

`src/index.js`:

```js
require("es5-ext/array/#/contains");
```

`test.js`:

```js
const path = require("path");
const { cruise } = require("dependency-cruiser");
const ROOT_DIR = path.join(__dirname, "src");
const ARRAY_OF_FILES_AND_DIRS_TO_CRUISE = [ROOT_DIR];
const cruiseResult = cruise(ARRAY_OF_FILES_AND_DIRS_TO_CRUISE);
console.log(JSON.stringify(cruiseResult, null, 4));
```

The result of `$ node test.js`

```json
{
    "output": {
        "modules": [
            {
                "source": "src/index.js",
                "dependencies": [
                    {
                        "resolved": "node_modules/es5-ext/array/index.js#/contains",
                        "coreModule": false,
                        "followable": false,
                        "couldNotResolve": true,
                        "dependencyTypes": [
                            "npm"
                        ],
                        "module": "es5-ext/array/#/contains",
                        "moduleSystem": "cjs",
                        "dynamic": false,
                        "exoticallyRequired": false,
                        "matchesDoNotFollow": false,
                        "circular": false,
                        "valid": true
                    }
                ],
                "orphan": false,
                "valid": true
            },
            {
                "source": "node_modules/es5-ext/array/index.js#/contains",
                "followable": false,
                "coreModule": false,
                "couldNotResolve": true,
                "matchesDoNotFollow": false,
                "dependencyTypes": [
                    "npm"
                ],
                "dependencies": [],
                "orphan": false,
                "valid": true
            }
        ],
        "summary": {
            "violations": [],
            "error": 0,
            "warn": 0,
            "info": 0,
            "totalCruised": 2,
            "totalDependenciesCruised": 1,
            "optionsUsed": {
                "combinedDependencies": false,
                "externalModuleResolutionStrategy": "node_modules",
                "moduleSystems": [
                    "amd",
                    "cjs",
                    "es6",
                    "tsd"
                ],
                "preserveSymlinks": false,
                "tsPreCompilationDeps": false,
                "exoticRequireStrings": [],
                "args": "src"
            }
        }
    },
    "exitCode": 0
}
```

- `module` field is correct
- `resolved` and `source` is wrong

### Context

Related: https://github.com/azu/express-router-dependency-graph/issues/2

### Your Environment

- Version used: 9.26.1
- Node version: v14.16.1
- Operating System and version:
- Link to your project: 
  - https://github.com/azu/express-router-dependency-graph
  - https://github.com/azu/dependency-cruiser-sharp-bug

**Comment by sverweij** [comment] 2021-05-03 10:44
Hi @azu - thanks for raising this issue. It seems a duplicate of #429. The root cause is an [issue within enhanced-resolve](https://github.com/webpack/enhanced-resolve/issues/282). Some clicking learns it might have been fixed recently, so I’ll try tonight.

There is a very noticeable performance degradation with enhanced-resolve versions later than 5.1.0 - so if there’s a fix it might present a dillema.

I’ll close this issue and follow up in #429

**Closed by sverweij** 2021-05-03 10:44 UTC
