### ISSUE TITLE
Feature request: Support for Typescript v5

### ISSUE THREAD

**Issue by lukeapage** [sverweij/dependency-cruiser#759] opened 2023-03-17 11:04 UTC
I've tested with TS 5 and it appears to work (manually changing meta.js to support ts 5).

Can we get a release with this?

**Comment by sverweij** [comment] 2023-03-17 18:19
Hi @lukeapage - thanks for the suggestion (and the pull request!). 

I've been eyeing the TypeScript 5.x releases & their release page closely, and dependency-cruiser should indeed keep working correctly as long as there's not yet one of the newer resolution features involved (or maybe it will, but at least some work will be required to prove that :-) ). 

I'll go over the PR and see if it's possible to make it part of the next release (somewhere this weekend D.v.)

**Comment by sverweij** [comment] 2023-03-17 19:40
Update: PR is merged. Additionally I've ran dependency-cruiser's non-regression test suite (+ adjacent checks) with TypeScript 5.0.2 and everything indeed still works :-)

**Comment by sverweij** [comment] 2023-03-17 20:07
@lukeapage Since a few minutes you can use `dependency-cruiser@12.10.2` which includes your update. Thanks again!

**Closed by sverweij** 2023-03-17 20:07 UTC

**Comment by lukeapage** [comment] 2023-03-17 20:37
More thanks to you, you did all the work. Thanks for a great package.

**Comment by sverweij** [comment] 2023-03-18 20:13
B.t.w. the [type-only re-exports](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#support-for-export-type) that are new in TypeScript 5.0 will be landing in dependency-cruiser soon as well: #761
