### ISSUE TITLE
Issue: reports 'not-to-unresolvable' error for usage of word 'import' in JSX in file

### ISSUE THREAD

**Issue by audunsol** [sverweij/dependency-cruiser#395] opened 2020-11-16 13:01 UTC
If I use the word `import` somewhere in a JSX-module, I get an  `not-to-unresolvable` error.

### Expected Behavior

It should only generate errors on module imports in JSX files.

### Current Behavior

It triggers an error on the usage of the word `import` in free text inside the JSX elements, like this:
```
error not-to-unresolvable: client/ReplicateIssueComponent.jsx → ✖
```

### Possible Solution

Not sure. Maybe try to detect and not parse JSX somehow?

### Steps to Reproduce (for bugs)

1. Add this file:

```jsx
import React from 'react';

export const ReplicateIssueComponent = props => {
  return (
    <>
    This usage of the word import in this string triggers the not-to-unresolvable error
    </>
  );
}
```
2. Runnig depcruise now gives this error:

```
error not-to-unresolvable: client/ReplicateIssueComponent.jsx → ✖
```

3. Remove the word `import` from the text string in `ReplicateIssueComponent.jsx` and observe that the error disappear.

Note that the following does not trigger the error:
```JSX
import React from 'react';

const someString = 'This usage of the word import in this string DOES NOT trigger the not-to-unresolvable error';

export const ReplicateIssueComponent = props => {
  return (
    <>
      {someString}
    </>
  );
}
```

### Context

We are just starting to experiment on using dependency cruiser on a large code base, trying to structurize our fight against cyclic and accidentally bad dependenies (from node server code to client and vice versa, from prod-code to test folder, etc) and found this awesome project, and it is really giving us a flying start by using the default config with a few more simple rules and a webpack config setup flag. It will hopefully soon be put into our CI pipeline.

But now we found some issues that we could not understand. We have at least 3 of these files. One of them is a big component is called `GenericDataImport.jsx` and has the word `import` 49 times in it, so I am not sure where to start on that one if we have to work around this bug.

### Your Environment

- Version used: `^9.17.0`
- Node version: `v12.19.0`
- Operating System and version: Ubuntu 20.04.1 LTS running via WSL on Windows 10
- Link to your project: <not publicly available>

**Comment by audunsol** [comment] 2020-11-16 13:49
Worked around the issue for now by manually excluding our 3 relevant JSX-files from that particular rule.

When thinking about it, our webpack build will fail for unresolveable imports anyway, so any potential issues that should be detected by this rule should be detectable earlier in our pipeline anyway.

But the issue should probably be looked into still.

**Comment by sverweij** [comment] 2020-11-16 17:40
Hi @audunsol haven't had the time to reproduce this issue, looking at your source code it's definitely a bug in dependency-cruiser: currently dependency-cruiser uses the _loose_ variant of the acorn to parse jsx. This is exactly the type of issue a 'loose' parser will yield. Earlier on I've been looking to go the proper route (and use acorn-jsx), which will likely fix it.

**Comment by sverweij** [comment] 2020-11-16 19:31
@audunsol I just made a PR (☝️ ) and released a version with a _beta_ tag that contains a fix for this issue: `dependency-cruiser@9.17.1-beta-1`.

=> Could you let me know if it works for you?

When it does, I'll release it as a regular release (possibly tomorrow 🤞 ).

**Comment by audunsol** [comment] 2020-11-17 14:50
Hi @sverweij ! Thanks for quick fix (and sorry for my slower response). I have tested `9.17.1-beta-1` now and I can confirm that it solves most of the issues!

It seems to still trigger the error in the following case (not that it is a beautiful way to wite JSX, but apparently we still have it in our code base):

```JSX
import React from 'react';

export class ReplicateIssueComponent extends React.Component {
  renderSomethingElse = () => {
    return (
      <>The word import here still triggers the not-to-unresolvable error</>
    );
  };

  render = () => (
    <>
      {this.renderSomethingElse()}
      This usage of the word import in this string does no longer trigger the
      not-to-unresolvable error (at version 9.17.1-beta-1)
    </>
  );
}
```

**Comment by sverweij** [comment] 2020-11-18 19:56
Hi @audunsol thanks for the feedback. Root cause of the error seems to be that acorn thinks the above jsx is not valid (I see it locally, but if you paste it in [astexplorer](https://astexplorer.net/#/gist/11112383914251fe989271eb086fd47d/faad479f28ea71fb2bdc9a0b3fc8445749996247) it shows up as well). If javascript (or jsx in this case) can't be parsed, dependency-cruiser still lets it fall back to the 'loose' variant of the acorn parser. 

I did try a few of the other parsers and while most couldn't make sense of the above jsx either, some did (babel parser (IIRC react uses that one), flow, typescript) - I'll see if I can use one or more of them to also get it parsed.

**Comment by audunsol** [comment] 2020-11-19 11:00
Thanks @sverweij!

I understand if this is becoming some of an edge case here (at least after the #396), so just wanted to mention that it is understandable if the priority is set lower now.

Just for the record, in case someone else lands on this issue, our **workaround 1** right now is to simply exclude the offending file(s) from the rule like this:

```javascript
{
      name: 'not-to-unresolvable',
      comment:
        "This module depends on a module that cannot be found ('resolved to disk'). If it's an npm " +
        'module: add it to your package.json. In all other cases you likely already know what to do.',
      severity: 'error',
      from: {
        // Some manual explicit exclusions, in ordet to work around
        // https://github.com/sverweij/dependency-cruiser/issues/395
        pathNot: [
          'client/ReplicateIssueComponent.jsx',
        ]
      },
      to: {
        couldNotResolve: true
      }
    },
```

We haven't seen any other rules give spurious alerts on these components this far. Also, _real_ unresolvable dependencies (imports pointing to non existing modules) are usually captured earlier in our pipeline, as it will make the webpack/babel build fail, so it is not extremely important to have this rule for us.

After some testing on `9.17.1-beta-1`, I also found out that using functional components instead of class components seems to solve the problem as well. E.g. **workaround 2**:

```javascript
import React from 'react';

const ReplicateIssueComponent = (props) => {
  const renderSomethingElse = () => {
    return (
      <>The word import here no longer triggers the not-to-unresolvable error either (at version 9.17.1-beta-1)
      since it is now a functional component.</>
    );
  };

  return (
    <>
      {renderSomethingElse()}
      This usage of the word import in this string does no longer trigger the
      not-to-unresolvable error (at version 9.17.1-beta-1)
    </>
  );
}

export default ReplicateIssueComponent;
```

Finally, our team is now introducing own guideline to avoid these types of "render functions" (for the purpose of making code cleaner), and instead make separate components, so another **workaround (3)** will eventually be something like:

```javascript

// ReplicateIssueComponent.jsx :
import React from 'react';
import ReplicateIssueSubComponent from './ReplicateIssueSubComponent';

export class ReplicateIssueComponent extends React.Component {
  render = () => (
    <>
      <ReplicateIssueSubComponent />
      This usage of the word import in this string does no longer trigger the
      not-to-unresolvable error (at version 9.17.1-beta-1)
    </>
  );
}

// ReplicateIssueSubComponent.jsx :
import React from 'react';

const ReplicateIssueSubComponent = (props) => {
  return (
    <>The word import here does not trigger the not-to-unresolvable error either (at version 9.17.1-beta-1).</>
  );
};

export default ReplicateIssueSubComponent;
```

PS: thanks for a great tool!

**Comment by sverweij** [comment] 2020-11-19 17:30
@audunsol thanks for your feedback - really appreciate the detail.

Next steps:
- #396 will be merged soon (maybe after including some of your examples in the documentation so it's at least a _known_ limitation).
- I have a few ideas to use elements to make parsing (a.o.) jsx as close/ true to the environment dependency-cruiser is running in. They're slightly more involved though, so these might follow on later in separate PR's

(And thanks for the compliment - enjoy the tool, and if in using it you happen to find things that can be improved, know that I'm all ears!)

**Closed** 2020-11-19 18:43 UTC
Labels: bug

**Comment by biggyspender** [comment] 2026-07-07 16:28
Looks like this is still reproducible, at least in a TSX setup.

I hit the same `not-to-unresolvable` false positive in a pre-commit depcruise run and narrowed it down to plain JSX text containing the word `import`.

Environment here:
- dependency-cruiser `18.0.0`
- TypeScript `7.0.1-rc`
- Node `22.22.3`

Minimal failing repro:

```tsx
import { FC } from 'react';

export const Repro: FC = () => {
  return <h4>What happens when you import?</h4>;
};
```

Passing workaround:

```tsx
import { FC } from 'react';

export const Repro: FC = () => {
  return <h4>{'What happens when you import?'}</h4>;
};
```

Commands:

```sh
./node_modules/.bin/depcruise temp/depcruise-import-text-repro.tsx --config .dependency-cruiser.js --output-type err
./node_modules/.bin/depcruise temp/depcruise-import-text-workaround.tsx --config .dependency-cruiser.js --output-type err
```

Observed output:

```text
repro:

  error not-to-unresolvable: temp/depcruise-import-text-repro.tsx -> ✖

x 1 dependency violations (1 errors, 0 warnings). 3 modules, 2 dependencies cruised.

workaround:

✔ no dependency violations found (2 modules, 1 dependencies cruised)
```

So my understanding is the core issue from this ticket is still present: plain JSX text containing `import` is being treated as if it were part of a dependency edge, while the equivalent JSX string expression is not.

Happy to provide anything else useful if needed.

**Comment by sverweij** [comment] 2026-07-07 20:04
@biggyspender I've forked this to a separate issue as that's easier to keep track off - see my first thoughts over there.
