### ISSUE TITLE
could not resolve ts file which name contains ‘#’

### ISSUE THREAD

**Issue by woodgear** [sverweij/dependency-cruiser#429] opened 2021-01-22 04:20 UTC
### Expected Behavior

could not resolve ts file which name contains ‘#’

### Current Behavior

couldNotResolve return true

### Possible Solution

it seems like the problem of https://github.com/webpack/enhanced-resolve

### Steps to Reproduce (for bugs)

I have write a test to reproduce this bug, you may want to check it via https://github.com/sverweij/dependency-cruiser/compare/develop...woodgear:could-not-resolve?expand=1

### Your Environment

- Version used: 9.21.6
- Node version: v10.23.0
- Operating System and version: linux ubuntu 20.04
- Link to your project:

**Comment by woodgear** [comment] 2021-01-22 04:22
weird that only the ts test fail.

**Comment by sverweij** [comment] 2021-01-22 18:35
Hello @woodgear - thanks for raising this issue (+ the associated PR with the test case)!

I share your hunch it might be a defect in (dependency-cruiser's use of) the resolver. However, if this only occurs for TypeScript sources it could also be related to the way (dependency-cruiser treats) TypeScript. 

> OTOH - if I read the .spec well the test case for javascript [attempts to resolve `./hots`](https://github.com/woodgear/dependency-cruiser/blob/19cc9eecc00ff5071c9df9bb621f71d3af2a83c6/test/extract/resolve/index.spec.js#L582) - where it likely meant to resolve `./#a`? 

=> Out of curiosity:  in what situation do you bump into `#`'s in filenames?

**Comment by woodgear** [comment] 2021-01-25 02:02
i have no idea。it was a legacy code. but it seems like a testcase relate to a bug which have a id name like #1234 .

**Comment by sverweij** [comment] 2021-01-31 21:06
hi @woodgear - it did take some time before I was able to get to this, sorry about that. I've stepped a test case through a debugger and see it's indeed going wrong in enhanced-resolve (as was your hunch already).

Next step'd be to raise an issue with enhanced-resolve with a two minimal reproduction samples; one for files _starting_ with a `#`, and one for files _containing_ `#` as both have different behaviours (the former tries to resolve `./index.js#i-start-with-a-hashmark` (which typically does not exist) the latter just doesn't resolve the file period).

> enhanced-resolve seems to treat `#` as a character for special purposes e.g. ref [Resolver.js#L282](https://github.com/webpack/enhanced-resolve/blob/ff16fc2854f0960093142297af376c67777bb2f4/lib/Resolver.js#L282)
> and the code for package.json export fields e.g. in [util/entrypoints.js](https://github.com/webpack/enhanced-resolve/blob/02d99a2e6852adaf43fecfc3fed14d8d5c8df10b/lib/util/entrypoints.js) and tests on export fields in [test/exportsFields.js](https://github.com/webpack/enhanced-resolve/blob/02d99a2e6852adaf43fecfc3fed14d8d5c8df10b/test/exportsField.js)

**Comment by woodgear** [comment] 2021-02-01 03:57
https://github.com/webpack/enhanced-resolve/issues/282

**Comment by sverweij** [comment] 2021-05-03 21:43
It seems there is a fix for webpack/enhanced-resolve#282 (implemented as a solution for webpack/webpack/issues/12156) I've tried it, but enhanced-resolve still inserts a NULL character in front of any `#` (`./path/to/#/thing` still resolves to `path/to/\u0000#/thing.js`). This time it looks like we can hack around it, though, by replacing all NULL characters in resolved strings with the empty string (working version with UT in [this branch](https://github.com/sverweij/dependency-cruiser/tree/bugfix/work-around-enhanced-resolves-hashmark-in-filenames-problem)).

The enhanced-resolve version with the 'fix' makes dependency-cruiser run 30% (!) slower than with the version it's currently using, though (running `yarn test:load` and comparing before and after), so I've got to ponder whether this edge case is worth the performance hit - or whether it might be better first invest some time in ensuring enhanced-resolve runs at its previous speed (either by param tweaking, if possible, or by making a PR on enhanced-resolve, again, when possible).

**Comment by sverweij** [comment] 2021-05-05 19:49
B.t.w. @woodgear / @azu I've published a beta version with the fix as a beta (dependency-cruiser@9.26.2-beta-1). Note that it's markedly slower than earlier version. Before promoting it to a regular _latest_ that  performance regression (that seems to have been caused by the introduction of enhanced-resolve@latest) will have to be addressed - and that can take some time. If you need `#` in filenames to be correct, this release should get you set in the mean time (let me know in case it doesn't, though).

**Comment by sverweij** [comment] 2021-05-08 17:06
There's a PR in [webpack/enhanced-resolve#292](https://github.com/webpack/enhanced-resolve/pull/292) that fixes the performance regression. I'll wait with merging the branch/ PR for the `#` until that one is merged.

**Closed** 2021-05-10 21:18 UTC
Labels: needs_fix_upstream

**Comment by sverweij** [comment] 2021-05-12 16:58
@woodgear / @azu The enhanced-resolve's performance fix was merged, and I've today release dependency-cruiser@10.0.1 which includes the fix for this issue. Share and enjoy!

**Comment by azu** [comment] 2021-05-12 23:12
Thanks!
