### ISSUE TITLE
Support webpack config resolution alias

### ISSUE THREAD

**Issue by bcomnes** [sverweij/dependency-cruiser#4] opened 2017-03-20 18:37 UTC
Its not uncommon to see module resolution aliases in webpack land:

```js
// webpack.config.js
resolve: {
    alias: {
      components: path.join(__dirname, 'src', 'components'),
      config: path.join(__dirname, 'src', 'config'),
      data: path.join(__dirname, 'src', 'data'),
      lib: path.join(__dirname, 'src', 'lib'),
      rdx: path.join(__dirname, 'src', 'rdx')
    }
  }
```

Is it possible to set up a rule to that can enable module resolution uisng webpack style aliases?  

I love this program.  Lots of fun.

**Comment by sverweij** [comment] 2017-03-20 21:00
Hmm, that would be a useful feature. Part of the target audience of dependency-cruiser probably lives in webpack land (a.o. Angular city, TypeScript province).

It can't be set up with a rule. 

However, I can probably add a webpack resolver. I've taken a peek into the webpack source code and it seems their resolution algorithm is in a separate module - I'll see if I can use that.

Glad you like it, b.t.w.!

**Comment by bcomnes** [comment] 2017-03-20 21:07
Ok cool!  Just thought I would check.  I'm not that big of a webpack user or webpack internals expert, so I probably won't ever get around to implementing it, but would definitely use it if someone else did.  Feel free to do whatever you want with this issue (close or keep open as an idea).

**Comment by sverweij** [comment] 2018-06-13 20:56
It's taken some time, but because recently this issue got some thumbs up, got referenced from twitter and because I'm now using webpack in some projects I decided to give it a go.

I've released a first rough draft of this feature on npm as beta. If you already want to test it `npm i dependency-cruiser@4.1.0-beta-0` will get you the version that has a `--webpack-config` option. This takes a reference to a webpack config file, and dependency-cruiser will its `resolve` key (which includes aliases) in resolving files to disk.

- cli documentation [here](https://github.com/sverweij/dependency-cruiser/blob/feature/add-webpack-config-resolution-alias/doc/cli.md#--webpack-config-use-the-resolution-options-of-a-webpack-configuration)
- Progress information in PR #50

**Comment by bcomnes** [comment] 2018-06-14 00:12
Amazing!  Thank you ✌️

**Comment by sverweij** [comment] 2018-06-23 10:47
@bcomnes c.s. I've just published version `4.1.0` to npm which contains the webpack-config option (command line as well as `.dependency-cruiser.json`), and which should suffice to close this issue.
- General description in the [cli documentation](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/cli.md#--webpack-config-use-the-resolution-options-of-a-webpack-configuration)
- Scope in the [FAQ](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/faq.md#does-this-work-with-webpack-configs-eg-alias-and-module)

If you have feedback on use (good, bad or ugly) I'm curious to hear of it.

**Comment by bcomnes** [comment] 2018-06-25 23:31
Unfortunately I haven't had time to play with this yet 😫

**Closed** 2018-06-26 15:03 UTC
Labels: enhancement

**Comment by akougblenou** [comment] 2019-12-17 11:02
Hi, I have just tried this feature passing the command:

```
depcruise --webpack-config ./webpack/webpack.common.js --validate .dependency-cruiser.json src
```
But I still got these flagged: 
```
  warn not-to-unresolvable: src/components/pages/Home.js → #components/molecules
  warn not-to-unresolvable: src/components/pages/Admin/UserUpdate.test.js → #devtools
  warn not-to-unresolvable: src/components/pages/Admin/UserUpdate.js → #services
  warn not-to-unresolvable: src/components/pages/Admin/UserUpdate.js → #components/templates
  warn not-to-unresolvable: src/components/pages/Admin/UserUpdate.js → #components/molecules
  warn not-to-unresolvable: src/components/pages/Admin/UserHub.test.js → #devtools
  warn not-to-unresolvable: src/components/pages/Admin/UserHub.js → #services
  warn not-to-unresolvable: src/components/pages/Admin/UserHub.js → #hooks
  warn not-to-unresolvable: src/components/pages/Admin/UserHub.js → #components/templates
```
Where all of the paths starting with # refer to aliases that are stated inside webpack.common.js
Am I missing something ?

**Comment by sverweij** [comment] 2019-12-17 11:25
@akougblenou I'd expect that to work. Could you share your repo or (if that's not possible) a minimal reproduction repo and/ or your webpack config + or two of the sources (e.g. the src/components/pages/Home.js and #components/molecules mentioned above)?

**Comment by sverweij** [comment] 2019-12-17 12:27
@akougblenou I've set up a [minimal reproduction repo](https://github.com/sverweij/repro-repo-dependency-cruiser-issue-4-ii) but wasn't able to replicate your issue (see e.g. the sample run in [this GitHub workflow](https://github.com/sverweij/repro-repo-dependency-cruiser-issue-4-ii/commit/bb934b61f3da8e3586b67e3c6685ffa5a4d7944b/checks?check_suite_id=362458072)). 

It's still possible you've bumped into a bug in dependency-cruiser, but I'll need something that replicates your issue in order to fix it...

**Comment by akougblenou** [comment] 2019-12-17 15:35
I'll try to work on something and have it here for tomorrow (as I cannot share my repo), thanks @sverweij

**Comment by akougblenou** [comment] 2019-12-24 11:57
Hi @sverweij sorry for all the time it took to put this together, the last few days in France have been hectic.
You can find the repo [here](https://github.com/akougblenou/depcruiser-app), I made it private so I guess you'd have to request access for it.
Thanks again for your help and enjoy the holidays !

**Comment by sverweij** [comment] 2019-12-24 12:34
Pas de problème @akougblenou, je comprends.

Anyways - thanks for the repo - as you predicted it's 404'ing on me. Can you add me as a collaborator?

**Comment by akougblenou** [comment] 2019-12-26 11:47
You should have received an invite @sverweij

**Comment by sverweij** [comment] 2019-12-27 20:58
Hi @akougblenou I've taken a peek and see what's going on - the entries in the webpack config don't point to existing files. E.g. the alias for `'#services'` is currently `path.join(__dirname, 'src', 'services'),`. As the webpack config resides in the `webpack` folder, this resolves to `webpack/src/services`. I've updated the webpack config to have `..` between `__dirname` and `src` - and dependency-cruiser works as expected.

I've made PR on the private repo with these changes & some other config.

HTH

> I also checked why despite this webpack still correctly assembles the app & runs it. It turns out there's a `.babelrc` in the root that has the same alias names, that do resolve to existing file names. There's a webpack loader (babel-loader) in both  `webpack/webpack.dev.js` and `webpack/webpack.prod.js` that applies the transformation before it's even handed to the webpack resolver, so the aliases in `webpack/webpack.common.js` don't have an effect during webpacking ...

**Comment by akougblenou** [comment] 2019-12-28 16:49
OK I see I wrote the paths similarly to the resolvers included in the babelrc's resolvers, but then the paths were wrong, I'll correct the paths and try once more, thanks a lot @sverweij !
