### ISSUE TITLE
Bug report: importing sub package from package with an exports section yields not-to-unresolvable

### ISSUE THREAD

**Issue by hckhanh** [sverweij/dependency-cruiser#338] opened 2020-07-28 08:19 UTC
I upgrade to the newer version and receive this error:

```bash
error not-to-unresolvable
```

 I am using [nanoid](https://github.com/ai/nanoid) package.

```js
const { customAlphabet } = require("nanoid/async");
const { nanoid } = require("nanoid/async");
```

I have to change `not-to-unresolvable` from `error` to `warn` for now.

**Comment by sverweij** [comment] 2020-07-28 09:38
@hckhanh - thanks for reporting this! I've been able to reproduce it.
There will be a release which fixes this issue  tonight (GMT+1)

**Comment by sverweij** [comment] 2020-07-28 18:34
Root cause found. enhanced-resolve now heeds the `exports` field in (in this case) nanoid's package.json. I've changed that back to the previous behaviour. PR & release will follow suit.

### background information for later reference

The message enhanced-resolve throws is:

```
Error: Package path ./async is not exported from package /Users/me/something/node_modules/nanoid (see exports field in /Users/me/something/node_modules/nanoid/package.json)
```

It can't find `./async` it because it by default looks for the `exports["./async"].node` key in nanoid's package.json. nanoid does have an `exports["./async"].require`, key though.

There's three ways to handle this on dependency-cruiser's side:
- tell enhanced-resolve to use either the `require` key or both the `require` and `node` key (with the `conditionNames` field) - not quite sure that's going to march, though. When in browser land you might want to use `browser` and when using es modules it might need to be `import` (as in nanoid's package.json- or `mjs` or `ejs`, or whatever standard-ish has been landed on for es modules).
- ignore the exports field - reverting back to the previous behaviour (and sort out the stuff in the point above for a later release).

> - [ ] Research for later: is there a standard for the exports condition names?

**Closed** 2020-07-28 20:18 UTC

**Comment by sverweij** [comment] 2020-07-28 20:29
@hckhanh thanks again for reporting this issue - the detail of the offending imports made finding the root cause a lot easier!

When you read this `dependency-cruiser@9.9.4` that includes the fix should've been published on npm.
