### ISSUE TITLE
Issue: Cannot resolve PnP `virtual:` dependencies

### ISSUE THREAD

**Issue by heejongahn** [sverweij/dependency-cruiser#471] opened 2021-06-24 09:21 UTC
Here's [reproduction](https://github.com/heejongahn/depcruise-virtual-deps-repro):

* `@applications/app` is depending on `@packages/shared`. [source](https://github.com/heejongahn/depcruise-virtual-deps-repro/blob/master/%40applications/app/package.json#L11)
* It's also referencing the package inside code. [source](https://github.com/heejongahn/depcruise-virtual-deps-repro/blob/master/%40applications/app/pages/index.tsx#L5)
* However, [the resulting graph](https://github.com/heejongahn/depcruise-virtual-deps-repro/blob/master/deps-graph.png) from `yarn deps:generate` does not include corresponding edge.

I first suspected the issue is that`dependency-cruiser` cannot correctly resolve [workspace ranged](https://yarnpkg.com/features/workspaces#workspace-ranges-workspace) dependency.

However, as examining my company's (much more complicated) real-world example, I found out that it's more likely related to [`virtual:` dependency declaration](https://github.com/heejongahn/depcruise-virtual-deps-repro/blob/master/.pnp.js#L63) in `.pnp.js`. Probably that's also the reason why `next` is marked by `not-to-unresolvable` rule, [while actually being declared as dependency](https://github.com/heejongahn/depcruise-virtual-deps-repro/blob/master/.pnp.js#L68).

For packages declared as `workspace:packages/...`, the edge is correctly shown. 

### Expected Behavior

The dependencies declared by `virtual:` protocol in `.pnp.js` are correctly picked up by `dependency-cruiser`.

### Current Behavior

Those are not picked up by `dependency-cruiser`.

### Possible Solution

Unfortunately, I'm not very familiar with PnP details, so I lack any ideas here 😢 

### Steps to Reproduce (for bugs)

https://github.com/heejongahn/depcruise-virtual-deps-repro

### Context

I'd like to use `dependency-cruiser` in our CI environment to ensure that certain rule regarding the deps chain of our internal packages are respected.

### Your Environment

- Version used: 10.0.2
- Node version: 12.20.2
- Operating System and version: macOS Catalina (10.15.5(19F101))
- Link to your project: https://github.com/heejongahn/depcruise-virtual-deps-repro

```
$ yarn depcruise --info
  Supported:

    If you need a supported, but not enabled transpiler ('✖' below), just install
    it in the same folder dependency-cruiser is installed. E.g. 'npm i livescript'
    will enable livescript support if it's installed in your project folder.

  Transpilers:

    ✔ javascript (>es1)
    ✖ babel (>=7.0.0 <8.0.0)
    ✖ coffee-script (>=1.0.0 <2.0.0)
    ✖ coffeescript (>=1.0.0 <3.0.0)
    ✖ livescript (>=1.0.0 <2.0.0)
    ✖ svelte (>=3.0.0 <4.0.0)
    ✖ swc (>=1.0.0 <2.0.0)
    ✔ typescript (>=2.0.0 <5.0.0)
    ✖ vue-template-compiler (>=2.0.0 <3.0.0)

  Extensions:

    ✔ .js
    ✔ .cjs
    ✔ .mjs
    ✔ .jsx
    ✔ .ts
    ✔ .tsx
    ✔ .d.ts
    ✖ .ls
    ✖ .coffee
    ✖ .litcoffee
    ✖ .coffee.md
    ✖ .csx
    ✖ .cjsx
    ✖ .vue
    ✖ .svelte
```

**Comment by sverweij** [comment] 2021-06-27 18:30
Hi @heejongahn - thanks for raising this issue and for that nice reproduction repo! 

Indeed there's some  berry (/ yarn v2) module resolution going on that's not quite handled as expected. I did some tweaking in the .dependency-cruiser config and it seems the virtual dependency _is_ found. However, we'd expect it to go to `@packages/shared/src` instead of to yarn's internal representation (see picture below).

I suspect some resolution magic will have to be written or adapted - potentially in webpack's `enhanced-resolve` (which dependency-cruiser uses under the hood for module resolution) as well, but I haven't been able to dig any further yet.

![deps-graph](https://user-images.githubusercontent.com/4822597/123555392-c45d4080-d785-11eb-9d20-a7141ebf5d95.png)

Also there's something interesting going on with direct imports from the `nest` node module - I'll look into that as well.

**Comment by heejongahn** [comment] 2021-06-28 07:56
Thanks a lot for the quick response!

>  However, we'd expect it to go to @packages/shared/src instead of to yarn's internal representation

Yep, that would be much nicer.

If there's anything I can do to help, please let me know 🙏

**Comment by merceyz** [comment] 2021-07-19 13:22
> I suspect some resolution magic will have to be written or adapted - potentially in webpack's enhanced-resolve (which dependency-cruiser uses under the hood for module resolution) as well, but I haven't been able to dig any further yet.

The pnpapi exposes a method that allows you to get the real path

```js
const filepath = '/path/returned/by/enhanced-resolve';
const realPath = require('module').findPnpApi?.(filepath)?.resolveVirtual?.(filepath) ?? filepath;
```

https://yarnpkg.com/advanced/pnpapi#requiremodule
https://yarnpkg.com/advanced/pnpapi#resolvevirtual

Here are the docs on what a virtual package is https://yarnpkg.com/advanced/lexicon/#virtual-package

**Comment by sverweij** [comment] 2021-07-19 21:58
Thanks @merceyz  - that's very helpful!

**Comment by sverweij** [comment] 2021-08-08 19:09
hi @heejongahn it's been a while - sorry about that. Before I could start a fix on this issue I first had to address some other issues related to yarn (#480 and 9f6b697d which turned out to both be caused by https://github.com/yarnpkg/berry/issues/3136) and grok virtual dependencies  (thanks @merceyz for the links & the code snippet - that helped a lot).

Apart from virtual dependencies (which should work when #483 is merged), the dependencies from `next-env.d.ts` in your reproduction repo were bitten by an entirely unrelated bug (fixed in #484). 

These fixes and improvements are up on npm as `dependency-cruiser@10.1.0-beta-2` - let me know if it also fixes the issue in your real life repo.

> With `10.1.0-beta-2` the graphs in the reproduction repo now look like this:
>
>_The original one, aggregated_ 
> <img width="241" alt="image" src="https://user-images.githubusercontent.com/4822597/128642619-baecc5c7-8854-49a9-8e28-f75af078d9cb.png">
>
> _the more detailed one_
> <img width="711" alt="image" src="https://user-images.githubusercontent.com/4822597/128642474-0a1327dc-b18d-4c51-a7fc-46e6bacdc823.png">
> 
> I made some tweaks and additions to the configuration in the repro repository so I could iterate faster in validating fixes; but also one or two that might improve the experience a bit in general. I'll see if I can whip up a PR with some explanations.

**Closed** 2021-08-09 20:43 UTC
Labels: bug

**Comment by sverweij** [comment] 2021-08-10 18:49
(The fix for this issue is now also part of the regular dependency-cruiser release - as of version 10.1.0)

**Comment by heejongahn** [comment] 2021-09-07 01:35
Sorry my reply was too late. I finally had a chance to try this at our workplace repo and v10.2 works like a charm!

There were some weird problems regarding `react` and `styled-components` imports, but I think they're irrelevant with this one. (I'll try to file an issue when I could narrow down the reason.)

I really appreciate your response and the fix, and of course, the tool itself. Thanks a ton!
