### ISSUE TITLE
Issue: babel config exists but is not passed to babel

### ISSUE THREAD

**Issue by lwolle** [sverweij/dependency-cruiser#421] opened 2021-01-17 13:32 UTC
We have a TS project that uses TS only for type-checking and only uses babel for transpilation and module resolution. I tried passing  `babel.config.json` to dependency-cruiser as described in the documentation and always end up with an error. The situation is described below.

### Expected Behavior
I expect dependency-cruiser to pick up the babel config without errors, and use the babel output to create the dependency tree.

### Current Behavior
Even though there is a valid and supported babel config in the project root directory, following error message is emittted.

` ERROR: Configuration contains string/RegExp pattern, but no filename was passed to Babel`

### Steps to Reproduce (for bugs)

1. `git checkout https://github.com/lwolle/dep-cruise-babel-config-error.git`
2. `yarn install`
3.  `yarn cruise`

### Context
I have effectively used dependency-cruiser before, but haven't actively used it for a while. While generating the latest diagram I've encountered this issue. As described above, it's a TS codebase that only uses TS for type-checking and transpiles with babel. We've setup babel with "absolute imports" from starting from `root/src`, which plays well with the `baseUrl: .` in `tsconfig.json`. 

### Your Environment

- Version used: 9.21.6
- Node version:  12.14.1
- Operating System and version: macOS 10.15.1 Catalina
- Link to your project: [https://github.com/lwolle/dep-cruise-babel-config-error](Link to repro)

**Comment by sverweij** [comment] 2021-01-17 19:19
Hi @lwolle - thanks for raising this issue and the (excellent) reproduction example! With its help I've been able to locate the root cause of the error: under certain circumstances babel expects a filename together with the contents of the babel config. So in the next version dependency-cruiser will provide babel with that by default. Fix + unit tests work locally and a PR will be coming up shortly (linked to this issue ☝️  or 👇 soon).

> I've ran the fix against the repro-repo, but bumped into a new phenomenon. Babel seems to have trouble parsing (some of the) typescript in the repo. It doesn't have the issue on the cli so it's likely some misunderstanding between babel and dependency-cruiser. I'll dig into that next.

**Comment by sverweij** [comment] 2021-01-20 21:54
FYI: The (merged) fix for this issue is part of beta version `dependency-cruiser@9.21.7-beta-1` as well (just like the one for #422). 

> I've found a possible route to help the Babel API realise it's parsing typescript, which I'll pursue next

**Comment by sverweij** [comment] 2021-01-21 17:37
The fix is now part of the regular 'latest' releases (9.21.7 and up).

**Comment by lwolle** [comment] 2021-01-22 09:06
Thank you for picking up the report so quickly. Tried it out and behaves as expected. 🚀

**Comment by sverweij** [comment] 2021-01-22 20:30
@lwolle seems the issue with parsing typescript with babel is fixed as well (see PR :point_up: if you want the details on the solution). I've ran it against your reproduction repo and now get the expected graph without unexpected babel errors.

=> could you give it a spin and check if it works for you as well?

It's released as `dependency-cruiser@9.21.8-beta-1`.  When it works well enough (and D.v.) I'll  release it somewhere by the end of the weekend.

**Comment by sverweij** [comment] 2021-01-25 19:43
The fix is now also available in `dependency-cruiser@9.22.0` (released yesterday). I'm closing the issue as it seems that both the original issue and the thing we found later on have been resolved. Feel free to re-open if you still bump into one of them in the version containing the fix.

**Closed by sverweij** 2021-01-25 19:43 UTC
Labels: bug
